FROM kalilinux/kali-linux-docker

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y metasploit-framework
RUN apt-get install -y aircrack-ng
RUN apt-get install -y pciutils
RUN apt-get install -y net-tools
RUN apt-get install -y nmap
RUN apt-get install -y macchanger
RUN apt-get install -y zsh
RUN apt-get install -y bettercap
